version: '3.8'

services:
  backend:
    build: .
    container_name: mental-health-agent
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/mentalhealth
      - CO_API_KEY=${CO_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      # (add any other env vars you actually use)
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
