version: '3.8'

services:
  nutritionist:
    image: nutritionist-backend
    container_name: tummytales-nutritionist
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s